[package]
name = "numers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "numerslib"
path = "src/lib.rs"
doctest = false


[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
num = "0.4.1"
